### PR TITLE
Sourcing images from Swift S3

### PR DESCRIPTION
**Pull request by SaschaAdler**
Upgrades Cantaloupe to 4.1.2; uses S3Source to find images; uses BasicLookupStrategy to look images up (since we no longer need to hash on paths).

### CODE REVIEW

**Comment by SaschaAdler** [comment]
Also solves #10.

**Comment by SaschaAdler** [comment]
@RussellMcOrmond I had to merge some conflicts; let me know if you spot any problems.

**Comment by RussellMcOrmond** [comment]
I don't think we use 'config.json' any more, which is why it might have been removed (and became a conflict).

I'm assuming you have reviewed the changes that I've been making, and are fine with them?  What we have at the moment is a compose between an Apache and Cantaloupe containers, with only port 80 on Apache being exposed externally.

**Comment by SaschaAdler** [comment]
Yup. Everything looks good to me.

It's probably a good idea to keep `config.json` in `.gitignore` in the event that it's still sitting in someone's working repository, so that it doesn't get accidentally committed.

**Review by RussellMcOrmond — APPROVED** [review]
Looks good to me.  We can discuss other issues after the merge.

**Pull request merged**
