### PR TITLE
If provided with a noid, looks it up in the canvas database

### PR DESCRIPTION
**Pull request by SaschaAdler**
Self-explanatory, I think.

This is SPLIT.9.7.

### CODE REVIEW

**Review by RussellMcOrmond — APPROVED** [review]
Tested on multiple servers.   Looks great.

In short term I believe this means that the <aip>/data/sip/data/filename.ext is being looked up in CouchDB for the old style, but that isn't worth making the code complex in order to optimise.

**Comment by SaschaAdler** [comment]
I've fixed up the URI escaping a bit. Seems to work on my end.

**Comment by RussellMcOrmond** [comment]
I'm just looking in the logs and noticing a number of odd messages.

I believe with an auth_token cookie in .canadiana.ca that https://image-cheddar.canadiana.ca/iiif/2/oocihm.8_00142_1%2Fdata%2Fsip%2Fdata%2Ffiles%2F0040.jpg/info.json should work.  What I'm getting is a forbidden.

```
22:42:55.561 [qtp1032000752-3000] INFO  e.i.l.c.r.i.v.InformationResource - Handling GET /iiif/2/oocihm.8_00142_1%2Fdata%2Fsip%2Fdata%2Ffiles%2F0040.jpg/info.json
JWT cannot be decoded with https://auth.canadiana.ca/'s secret key.
Unauthorized: JWT could not be validated.
22:42:55.563 [qtp1032000752-3000] INFO  e.i.l.c.r.ErrorResource - Handling GET /iiif/2/oocihm.8_00142_1%2Fdata%2Fsip%2Fdata%2Ffiles%2F0040.jpg/info.json
```


With that admin JWT cookie I also would have assumed that any of the requests that work with the token= from CAP would work without that get parameter as well.

**Comment by RussellMcOrmond** [comment]
Ignore last note..

Oops: https://github.com/crkn-rcdr/puppet/pull/71/commits/609a94b51691ea9e8312e14257a8256df18bbd2f

**Comment by RussellMcOrmond** [comment]
I don't know if this is related at all, but we get logs like this regularly (a redirect from an image URL to a page that is not authorized).

Is this something our page viewer does, or is this someone running something else?

```
Sep  1 23:02:21 172.17.0.2 haproxy[54]: 104.244.73.43:38851 [01/Sep/2020:23:02:21.809] public~ cantaloupe/local 0/0/0/2/2 303 422 - - ---- 6/6/0/0/0 0/0 {https|image-iris.canadiana.ca} "HEAD /iiif/2/oocihm.lac_reel_c6744%2Fdata%2Fsip%2Fdata%2Ffiles%2Fc-6744-00621.jpg HTTP/1.1"
Sep  1 23:02:24 172.17.0.2 haproxy[54]: 185.220.101.145:9410 [01/Sep/2020:23:02:24.349] public~ cantaloupe/local 0/0/0/6/6 403 324 - - ---- 6/6/0/0/0 0/0 {https|image-iris.canadiana.ca} "HEAD /iiif/2/oocihm.lac_reel_c6744%2Fdata%2Fsip%2Fdata%2Ffiles%2Fc-6744-00621.jpg/info.json HTTP/1.1"
Sep  1 23:02:26 172.17.0.2 haproxy[54]: 185.220.101.144:29888 [01/Sep/2020:23:02:26.761] public~ cantaloupe/local 0/0/0/2/2 303 422 - - ---- 4/4/1/1/0 0/0 {https|image-iris.canadiana.ca} "HEAD /iiif/2/oocihm.lac_reel_c6744%2Fdata%2Fsip%2Fdata%2Ffiles%2Fc-6744-00621.jpg HTTP/1.1"
Sep  1 23:02:29 172.17.0.2 haproxy[54]: 185.220.101.144:10330 [01/Sep/2020:23:02:29.016] public~ cantaloupe/local 0/0/1/7/8 403 324 - - ---- 4/4/0/0/0 0/0 {https|image-iris.canadiana.ca} "HEAD /iiif/2/oocihm.lac_reel_c6744%2Fdata%2Fsip%2Fdata%2Ffiles%2Fc-6744-00621.jpg/info.json HTTP/1.1"
```

**Comment by SaschaAdler** [comment]
Our page viewer doesn't make HEAD requests on things, and so I'm not sure what that is.

**Pull request merged**
